spring:
  datasource:
    url: jdbc:mysql://localhost:3306/worktopia_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        hibernate:
          format_sql: true
    open-in-view: false
  application:
    name: worktopia
  mail:
    host: smtp.gmail.com
    port: 587 #465
    properties:
      mail:
        smtp:
          trust: "*"
        auth: false  # Disable auth unless you configured MailDev with credentials
        starttls:
          enable: false  # MailDev usually doesn't support TLS in local dev
    username: #ton adresse mail
    password: #
server:
  port: 8081
  servlet:
    context-path: /api/
application:
  security:
    jwt:
      secret-key: 36541236987412589632587412563214569874563211mySecretKeyGenerator78
      expiration: 86400000
  upload-payslip-dir: payslips
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
