spring:
  profiles:
    active: dev #remplacer dev par prod pour utiliser le fichier de configuration application-prod.yml pour l'envoi de mail via gmail
  application:
    name: worktopia
server:
  port: 8081
  servlet:
    context-path: /api/

logging:
  level:
    org:
      springframework:
        mail: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE